<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\redts_f_offices;

class officeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        redts_f_offices::create(['id' => 1, 'region_id' => 7, 'slug' => 'R5-ORD', 'office' => 'ORD', 'full_office_name' => 'Office of the Regional Director', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 2, 'region_id' => 7, 'slug' => 'R5-SCIS', 'office' => 'SCIS', 'full_office_name' => 'Strategic Communication Initiative Service', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 3, 'region_id' => 7, 'slug' => 'R5-OARDMS', 'office' => 'OARDMS', 'full_office_name' => 'Office of the Assistant Regional Director for Management Services', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 4, 'region_id' => 7, 'slug' => 'R5-OARDMS-PMD', 'office' => 'PMD', 'full_office_name' => 'Planning and Management Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 5, 'region_id' => 7, 'slug' => 'R5-OARDMS-PMD-ICTS', 'office' => 'PMD', 'full_office_name' => 'Information and Communications Technology Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 6, 'region_id' => 7, 'slug' => 'R5-OARDMS-PMD-MES', 'office' => 'PMD', 'full_office_name' => 'Monitoring and Evaluation Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 7, 'region_id' => 7, 'slug' => 'R5-OARDMS-PMD-PPS', 'office' => 'PMD', 'full_office_name' => 'Planning and Programming Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 8, 'region_id' => 7, 'slug' => 'R5-OARDMS-LEGAL', 'office' => 'LEGAL', 'full_office_name' => 'Legal Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 9, 'region_id' => 7, 'slug' => 'R5-OARDMS-LEGAL-IS', 'office' => 'LEGAL', 'full_office_name' => 'Investigation Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 10, 'region_id' => 7, 'slug' => 'R5-OARDMS-LEGAL-ERLS', 'office' => 'LEGAL', 'full_office_name' => 'Environment, Research Legislation Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 11, 'region_id' => 7, 'slug' => 'R5-OARDMS-LEGAL-LAS', 'office' => 'LEGAL', 'full_office_name' => 'Litigation and Adjudication Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 12, 'region_id' => 7, 'slug' => 'R5-OARDMS-FINANCE', 'office' => 'FIN', 'full_office_name' => 'Finance Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 13, 'region_id' => 7, 'slug' => 'R5-OARDMS-FINANCE-BFS', 'office' => 'FIN.Budget', 'full_office_name' => 'Budget and Fiscal Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 14, 'region_id' => 7, 'slug' => 'R5-OARDMS-FINANCE-AS', 'office' => 'FIN.Accounting', 'full_office_name' => 'Accounting Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 15, 'region_id' => 7, 'slug' => 'R5-OARDMS-ADMIN', 'office' => 'AD', 'full_office_name' => 'Administrative Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 16, 'region_id' => 7, 'slug' => 'R5-OARDMS-ADMIN-PS', 'office' => 'AD.Personnel', 'full_office_name' => 'Personnel Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 17, 'region_id' => 7, 'slug' => 'R5-OARDMS-ADMIN-HRDS', 'office' => 'AD.HRDS', 'full_office_name' => 'Human Resource Development Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 18, 'region_id' => 7, 'slug' => 'R5-OARDMS-ADMIN-GSS', 'office' => 'AD.GSS', 'full_office_name' => 'General Services Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 19, 'region_id' => 7, 'slug' => 'R5-OARDMS-ADMIN-GSS-RU', 'office' => 'AD.Records', 'full_office_name' => 'Records Unit', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 20, 'region_id' => 7, 'slug' => 'R5-OARDMS-ADMIN-PROC', 'office' => 'AD.Procurement', 'full_office_name' => 'Procurement Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 21, 'region_id' => 7, 'slug' => 'R5-OARDMS-ADMIN-CASHIER', 'office' => 'AD.Cashier', 'full_office_name' => 'Cashier Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 22, 'region_id' => 7, 'slug' => 'R5-OARDTS', 'office' => 'OARDTS', 'full_office_name' => 'Office of the Assistant Regional Director in Technical Services', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 23, 'region_id' => 7, 'slug' => 'R5-OARDTS-LPDD', 'office' => 'LPDD', 'full_office_name' => 'Licenses, Patents and Deeds Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 24, 'region_id' => 7, 'slug' => 'R5-OARDTS-LPDD-WRUS', 'office' => 'LPDD.Water', 'full_office_name' => 'Water Resource Utilization Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 25, 'region_id' => 7, 'slug' => 'R5-OARDTS-LPDD-PDS', 'office' => 'LPDD.PDS', 'full_office_name' => 'Patents and Deeds Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 26, 'region_id' => 7, 'slug' => 'R5-OARDTS-LPDD-FUS', 'office' => 'LPDD.FUS', 'full_office_name' => 'Forest Utilizatoin Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 27, 'region_id' => 7, 'slug' => 'R5-OARDTS-LPDD-WRPS', 'office' => 'LPDD.WRPS', 'full_office_name' => 'Wildlife Resource Permitting Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 28, 'region_id' => 7, 'slug' => 'R5-OARDTS-SMD', 'office' => 'SMD', 'full_office_name' => 'Surveys and Mapping Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 29, 'region_id' => 7, 'slug' => 'R5-OARDTS-SMD-SCS', 'office' => 'SMD.SCS', 'full_office_name' => 'Surveys and Control Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 30, 'region_id' => 7, 'slug' => 'R5-OARDTS-SMD-LESS', 'office' => 'SMD.LESS', 'full_office_name' => 'Land Evaluation Survey Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 31, 'region_id' => 7, 'slug' => 'R5-OARDTS-SMD-ASCS', 'office' => 'SMD.Aggregate', 'full_office_name' => 'Aggregates Surveys and Correction Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 32, 'region_id' => 7, 'slug' => 'R5-OARDTS-SMD-OOSS', 'office' => 'SMD.OOSS', 'full_office_name' => 'Original and Other Surveys Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 33, 'region_id' => 7, 'slug' => 'R5-OARDTS-SMD-LRS', 'office' => 'SMD.LRS', 'full_office_name' => 'Land Records Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 34, 'region_id' => 7, 'slug' => 'R5-OARDTS-CDD', 'office' => 'CDD', 'full_office_name' => 'Conservation and Development Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 35, 'region_id' => 7, 'slug' => 'R5-OARDTS-CDD-PFMS', 'office' => 'CDD.PFMS', 'full_office_name' => 'Production Forest Management Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 36, 'region_id' => 7, 'slug' => 'R5-OARDTS-CDD-CRFMS', 'office' => 'CDD.Coastal', 'full_office_name' => 'Coastal Resource and Foreshore Mgt Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 37, 'region_id' => 7, 'slug' => 'R5-OARDTS-CDD-PAMBCS', 'office' => 'CDD.PA', 'full_office_name' => 'PA Mgt and Biodiversity Conservation Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 38, 'region_id' => 7, 'slug' => 'R5-OARDTS-ED', 'office' => 'ED', 'full_office_name' => 'Enforcement Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 39, 'region_id' => 7, 'slug' => 'R5-OARDTS-ED-CMIS', 'office' => 'ED.Compliance', 'full_office_name' => 'Compliance Monitoring and Investigation Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 40, 'region_id' => 7, 'slug' => 'R5-OARDTS-ED-SIS', 'office' => 'ED.Surveillance', 'full_office_name' => 'Surveillance and Intelligence Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 41, 'region_id' => 7, 'slug' => 'R5-PENRO-ALBAY', 'office' => 'P.Albay', 'full_office_name' => 'PENRO Albay', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Legazpi Port District, Legazpi City, Albay',]);
        redts_f_offices::create(['id' => 42, 'region_id' => 7, 'slug' => 'R5-PENRO-CSUR', 'office' => 'P.CSur', 'full_office_name' => 'PENRO Camarines Sur', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Panganiban Drive, Naga City, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 43, 'region_id' => 7, 'slug' => 'R5-PENRO-CNORTE', 'office' => 'P.CNorte', 'full_office_name' => 'PENRO Camarines Norte', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Dagondan, Daet, Camarines Norte',]);
        redts_f_offices::create(['id' => 44, 'region_id' => 7, 'slug' => 'R5-PENRO-MASBATE', 'office' => 'P.Masbate', 'full_office_name' => 'PENRO Masbate', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Zurbito Street, Masbate City',]);
        redts_f_offices::create(['id' => 45, 'region_id' => 7, 'slug' => 'R5-PENRO-CATNES', 'office' => 'P.Catnes', 'full_office_name' => 'PENRO Catanduanes', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'San Isidro Village, Virac, Catanduanes',]);
        redts_f_offices::create(['id' => 46, 'region_id' => 7, 'slug' => 'R5-PENRO-SORSOGON', 'office' => 'P.Sor', 'full_office_name' => 'PENRO Sorsogon', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'B. Road, Sorsogon City, Sorsogon',]);
        redts_f_offices::create(['id' => 47, 'region_id' => 7, 'slug' => 'R5-CENRO-GUINOBATAN', 'office' => 'C.GBTN', 'full_office_name' => 'CENRO Guinobatan', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Morera, Guinobatan, Albay',]);
        redts_f_offices::create(['id' => 48, 'region_id' => 7, 'slug' => 'R5-CENRO-IRIGA', 'office' => 'C.Iriga', 'full_office_name' => 'CENRO Iriga', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Iriga City, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 49, 'region_id' => 7, 'slug' => 'R5-CENRO-SIPOCOT', 'office' => 'C.Sipocot', 'full_office_name' => 'CENRO Sipocot', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Sipocot, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 50, 'region_id' => 7, 'slug' => 'R5-CENRO-GOA', 'office' => 'C.Goa', 'full_office_name' => 'CENRO Goa', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Catagbacan, Goa, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 51, 'region_id' => 7, 'slug' => 'R5-CENRO-MOBO', 'office' => 'C.Mobo', 'full_office_name' => 'CENRO Mobo', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Medina St, Mobo, Masbate',]); //updated
        redts_f_offices::create(['id' => 52, 'region_id' => 7, 'slug' => 'R5-CENRO-SANJACINTO', 'office' => 'C.SJ', 'full_office_name' => 'CENRO San Jacinto', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'San Jacinto, Masbate',]); //updated
        redts_f_offices::create(['id' => 53, 'region_id' => 7, 'slug' => 'R5-BAC', 'office' => 'RBAC', 'full_office_name' => 'RBAC', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 54, 'region_id' => 7, 'slug' => 'R5-TWG-INFRA-PROJ', 'office' => 'TWG.INFRA', 'full_office_name' => 'TWG Infrastructure Projects', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 55, 'region_id' => 7, 'slug' => 'R5-TWG-GOODS-SERV', 'office' => 'TWG.Goods', 'full_office_name' => 'TWG Goods and Services', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 56, 'region_id' => 7, 'slug' => 'R5-TWG-IT-EQ', 'office' => 'TWG.IT', 'full_office_name' => 'TWG IT Equipments', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 57, 'region_id' => 7, 'slug' => 'R5-TWG-CONSERV', 'office' => 'TWG.Consulting', 'full_office_name' => 'TWG Consulting Services', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 58, 'region_id' => 7, 'slug' => 'R5-TWG-NGP', 'office' => 'TWG.NGP', 'full_office_name' => 'TWG National Greening Program', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 59, 'region_id' => 7, 'slug' => 'R5-INS-INFRA-PROJ', 'office' => 'INS.INFRA', 'full_office_name' => 'Inspection Infrastructure Projects', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 60, 'region_id' => 7, 'slug' => 'R5-INS-GOODS-SERV', 'office' => 'INS.Goods', 'full_office_name' => 'Inspection Goods and Services', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 61, 'region_id' => 7, 'slug' => 'R5-INS-IT-EQ', 'office' => 'INS.IT', 'full_office_name' => 'Inspection IT Equipments', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 62, 'region_id' => 7, 'slug' => 'R5-INS-CONSERV', 'office' => 'INS.Consulting', 'full_office_name' => 'Inspection Consulting Services', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 63, 'region_id' => 7, 'slug' => 'R5-INS-NGP-T1', 'office' => 'INS.NGPT1', 'full_office_name' => 'Inspection National Greening Program Team 1', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 64, 'region_id' => 7, 'slug' => 'R5-INS-NGP-T2', 'office' => 'INS.NGPT2', 'full_office_name' => 'Inspection National Greening Program Team 2', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 65, 'region_id' => 7, 'slug' => 'R5-INS-NGP-T3', 'office' => 'INS.NGPT3', 'full_office_name' => 'Inspection National Greening Program Team 3', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 66, 'region_id' => 7, 'slug' => 'R5-INS-VEHICLE', 'office' => 'INS.Vehicle', 'full_office_name' => 'Inspection Vehicle', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 67, 'region_id' => 7, 'slug' => 'R5-CANVASSER1-AD', 'office' => 'Canvass.AD1', 'full_office_name' => 'Admin Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 68, 'region_id' => 7, 'slug' => 'R5-CANVASSER2-AD', 'office' => 'Canvass.AD2', 'full_office_name' => 'Admin Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 69, 'region_id' => 7, 'slug' => 'R5-CANVASSER-PMD', 'office' => 'Canvass.PMD', 'full_office_name' => 'Planning and Management Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 70, 'region_id' => 7, 'slug' => 'R5-CANVASSER-LEGAL', 'office' => 'Canvass.Legal', 'full_office_name' => 'Legal Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 71, 'region_id' => 7, 'slug' => 'R5-CANVASSER-SCIS', 'office' => 'Canvass.SCIS', 'full_office_name' => 'Strategic Communication Initiative Service', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 72, 'region_id' => 7, 'slug' => 'R5-CANVASSER-FD', 'office' => 'Canvass.FD', 'full_office_name' => 'Finance Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 73, 'region_id' => 7, 'slug' => 'R5-CANVASSER-CDD', 'office' => 'Canvass.CDD', 'full_office_name' => 'Conservation and Development Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 74, 'region_id' => 7, 'slug' => 'R5-CANVASSER-LPDD', 'office' => 'Canvass.LPDD', 'full_office_name' => 'Licenses, Patents and Deeds Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 75, 'region_id' => 7, 'slug' => 'R5-CANVASSER-ED', 'office' => 'Canvass.ED', 'full_office_name' => 'Enforcement Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 76, 'region_id' => 7, 'slug' => 'R5-CANVASSER-SMD', 'office' => 'Canvass.SMD', 'full_office_name' => 'Surveys and Mapping Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 77, 'region_id' => 7, 'slug' => 'R5-PENRO-Albay-MSD', 'office' => 'P.Albay.MSD', 'full_office_name' => 'Management Services Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Legazpi Port District, Legazpi City, Albay',]);
        redts_f_offices::create(['id' => 78, 'region_id' => 7, 'slug' => 'R5-PENRO-Albay-MSD-Admin', 'office' => 'P.Albay.Admin', 'full_office_name' => 'Administrative Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Legazpi Port District, Legazpi City, Albay',]);
        redts_f_offices::create(['id' => 79, 'region_id' => 7, 'slug' => 'R5-PENRO-Albay-MSD-Finance', 'office' => 'P.Albay.Finance', 'full_office_name' => 'Finance Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Legazpi Port District, Legazpi City, Albay',]);
        redts_f_offices::create(['id' => 80, 'region_id' => 7, 'slug' => 'R5-PENRO-Albay-Planning', 'office' => 'P.Albay.PMS', 'full_office_name' => 'Planning and Management Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Legazpi Port District, Legazpi City, Albay',]);
        redts_f_offices::create(['id' => 81, 'region_id' => 7, 'slug' => 'R5-PENRO-Albay-Records', 'office' => 'P.Albay.Records', 'full_office_name' => 'Records Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Legazpi Port District, Legazpi City, Albay',]);
        redts_f_offices::create(['id' => 82, 'region_id' => 7, 'slug' => 'R5-PENRO-Albay-TSD', 'office' => 'P.Albay.TSD', 'full_office_name' => 'Technical Services Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Legazpi Port District, Legazpi City, Albay',]);
        redts_f_offices::create(['id' => 83, 'region_id' => 7, 'slug' => 'R5-PENRO-Albay-TSD-Conservation', 'office' => 'P.Albay.CDS', 'full_office_name' => 'Conservation and Development Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Legazpi Port District, Legazpi City, Albay',]);
        redts_f_offices::create(['id' => 84, 'region_id' => 7, 'slug' => 'R5-PENRO-Albay-TSD-RLPDS', 'office' => 'P.Albay.RPS', 'full_office_name' => 'PENRO Albay Regulation and Permitting Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Legazpi Port District, Legazpi City, Albay',]);
        redts_f_offices::create(['id' => 85, 'region_id' => 7, 'slug' => 'R5-PENRO-Albay-TSD-Enforcement', 'office' => 'P.Albay.Enforcement', 'full_office_name' => 'Enforcement Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Legazpi Port District, Legazpi City, Albay',]);
        redts_f_offices::create(['id' => 86, 'region_id' => 7, 'slug' => 'R5-PENRO-CNorte-MSD', 'office' => 'P.Cn.MSD', 'full_office_name' => 'Management Services Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Daet, Camarines Norte',]); //updated
        redts_f_offices::create(['id' => 87, 'region_id' => 7, 'slug' => 'R5-PENRO-CNorte-MSD-Admin', 'office' => 'P.CN.Admin', 'full_office_name' => 'Administrative Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Daet, Camarines Norte',]); //updated
        redts_f_offices::create(['id' => 88, 'region_id' => 7, 'slug' => 'R5-PENRO-CNorte-MSD-Finance', 'office' => 'P.CN.Finance', 'full_office_name' => 'Finance Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Daet, Camarines Norte',]); //updated
        redts_f_offices::create(['id' => 89, 'region_id' => 7, 'slug' => 'R5-PENRO-CNorte-MSD-Planning', 'office' => 'P.CN.PMS', 'full_office_name' => 'Planning and Management Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Daet, Camarines Norte',]); //updated
        redts_f_offices::create(['id' => 90, 'region_id' => 7, 'slug' => 'R5-PENRO-CNorte-MSD-Records', 'office' => 'P.CN.Records', 'full_office_name' => 'Records Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Daet, Camarines Norte',]); //updated
        redts_f_offices::create(['id' => 91, 'region_id' => 7, 'slug' => 'R5-PENRO-CNorte-TSD', 'office' => 'P.CN.TSD', 'full_office_name' => 'Technical Services Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Daet, Camarines Norte',]); //updated
        redts_f_offices::create(['id' => 92, 'region_id' => 7, 'slug' => 'R5-PENRO-CNorte-TSD-Conservation', 'office' => 'P.CN.CDS', 'full_office_name' => 'Conservation and Development Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Daet, Camarines Norte',]); //updated
        redts_f_offices::create(['id' => 93, 'region_id' => 7, 'slug' => 'R5-PENRO-CNorte-TSD-RLPDS', 'office' => 'P.CN.RPS', 'full_office_name' => 'PENRO Camarines Norte Regulation and Permitting Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Daet, Camarines Norte',]); //updated
        redts_f_offices::create(['id' => 94, 'region_id' => 7, 'slug' => 'R5-PENRO-CNorte-TSD-Enforcement', 'office' => 'P.CN.Enforcement', 'full_office_name' => 'Enforcement Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Daet, Camarines Norte',]); //updated
        redts_f_offices::create(['id' => 95, 'region_id' => 7, 'slug' => 'R5-PENRO-CSur', 'office' => 'P.CSur', 'full_office_name' => 'PENRO Camarines Sur', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Panganiban Drive, Naga City, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 96, 'region_id' => 7, 'slug' => 'R5-PENRO-CSur-MSD', 'office' => 'P.CSur.MSD', 'full_office_name' => 'Management and Services Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Panganiban Drive, Naga City, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 97, 'region_id' => 7, 'slug' => 'R5-PENRO-CSur-MSD-Admin', 'office' => 'P.Csur.Admin', 'full_office_name' => 'Administrative Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Panganiban Drive, Naga City, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 98, 'region_id' => 7, 'slug' => 'R5-PENRO-CSur-MSD-Finance', 'office' => 'P.CSur.Finance', 'full_office_name' => 'Finance Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Panganiban Drive, Naga City, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 99, 'region_id' => 7, 'slug' => 'R5-PENRO-CSur-MSD-Planning', 'office' => 'P.CSur.PMS', 'full_office_name' => 'Planning and Management Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Panganiban Drive, Naga City, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 100, 'region_id' => 7, 'slug' => 'R5-PENRO-CSur-MSD-Records', 'office' => 'P.CSur.Records', 'full_office_name' => 'Records Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Panganiban Drive, Naga City, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 101, 'region_id' => 7, 'slug' => 'R5-PENRO-CSur-TSD', 'office' => 'P.CSur.TSD', 'full_office_name' => 'Tecnical services Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Panganiban Drive, Naga City, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 102, 'region_id' => 7, 'slug' => 'R5-PENRO-CSur-TSD-Conservation', 'office' => 'P.CSur.CDS', 'full_office_name' => 'Conservation and Development Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Panganiban Drive, Naga City, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 103, 'region_id' => 7, 'slug' => 'R5-PENRO-CSur-TSD-RLPDS', 'office' => 'P.CSur.RPS', 'full_office_name' => 'PENRO Camarines Sur Regulation and Permitting Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Panganiban Drive, Naga City, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 104, 'region_id' => 7, 'slug' => 'R5-PENRO-CSur-TSD-Enforment', 'office' => 'P.CSur.Enforcement', 'full_office_name' => 'Enforcement Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Panganiban Drive, Naga City, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 105, 'region_id' => 7, 'slug' => 'R5-PENRO-Catnes-MSD', 'office' => 'P.Catnes.MSD', 'full_office_name' => 'Management Services Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'San Isidro Village, Virac, Catanduanes',]); //updated
        redts_f_offices::create(['id' => 106, 'region_id' => 7, 'slug' => 'R5-PENRO-Catnes-MSD-Admin', 'office' => 'P.Catnes.Admin', 'full_office_name' => 'Administration Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'San Isidro Village, Virac, Catanduanes',]); //updated
        redts_f_offices::create(['id' => 107, 'region_id' => 7, 'slug' => 'R5-PENRO-Catnes-MSD-Finance', 'office' => 'P.Catnes.Finance', 'full_office_name' => 'Finance Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'San Isidro Village, Virac, Catanduanes',]); //updated
        redts_f_offices::create(['id' => 108, 'region_id' => 7, 'slug' => 'R5-PENRO-Catnes-MSD-Planning', 'office' => 'P.Catnes.PMS', 'full_office_name' => 'Planning and Management Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'San Isidro Village, Virac, Catanduanes',]); //update
        redts_f_offices::create(['id' => 109, 'region_id' => 7, 'slug' => 'R5-PENRO-Catnes-MSD-Records', 'office' => 'P.Catnes.Records', 'full_office_name' => 'Records Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'San Isidro Village, Virac, Catanduanes',]); //updated
        redts_f_offices::create(['id' => 110, 'region_id' => 7, 'slug' => 'R5-PENRO-Catnes-TSD', 'office' => 'P.Catnes_TSD', 'full_office_name' => 'Technical Services Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'San Isidro Village, Virac, Catanduanes',]); //updated
        redts_f_offices::create(['id' => 111, 'region_id' => 7, 'slug' => 'R5-PENRO-Catnes-TSD-Conservation', 'office' => 'P.Catnes.CDS', 'full_office_name' => 'Conservation and Development Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'San Isidro Village, Virac, Catanduanes',]); //updated
        redts_f_offices::create(['id' => 112, 'region_id' => 7, 'slug' => 'R5-PENRO-Catnes-TSD-RPS', 'office' => 'P.Catnes.RPS', 'full_office_name' => 'PENRO Catanduanes Regulation and Permitting Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'San Isidro Village, Virac, Catanduanes',]);
        redts_f_offices::create(['id' => 113, 'region_id' => 7, 'slug' => 'R5-PENRO-Catnes-TSD-Enforcement', 'office' => 'P.Catnes.Enforment', 'full_office_name' => 'Enforcement Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'San Isidro Village, Virac, Catanduanes',]);
        redts_f_offices::create(['id' => 114, 'region_id' => 7, 'slug' => 'R5-PENRO-Masbate-MSD', 'office' => 'P.Masbate.MSD', 'full_office_name' => 'Management Services Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Zurbito Street, Masbate City',]);
        redts_f_offices::create(['id' => 115, 'region_id' => 7, 'slug' => 'R5-PENRO-Masbate-MSD-Admin', 'office' => 'P.Masbate.Admin', 'full_office_name' => 'Administration Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Zurbito Street, Masbate City',]);
        redts_f_offices::create(['id' => 116, 'region_id' => 7, 'slug' => 'R5-PENRO-Masbate-MSD-Finance', 'office' => 'P.Masbate.Finance', 'full_office_name' => 'Finance Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Zurbito Street, Masbate City',]);
        redts_f_offices::create(['id' => 117, 'region_id' => 7, 'slug' => 'R5-PENRO-Masbate-MSD-Planning', 'office' => 'P.Masbate.PMS', 'full_office_name' => 'Planning and Management Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Zurbito Street, Masbate City',]);
        redts_f_offices::create(['id' => 118, 'region_id' => 7, 'slug' => 'R5-PENRO-Masbate-MSD-Records', 'office' => 'P.Masbate.Records', 'full_office_name' => 'Records Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Zurbito Street, Masbate City',]);
        redts_f_offices::create(['id' => 119, 'region_id' => 7, 'slug' => 'R5-PENRO-Masbate-TSD', 'office' => 'P.Masbate.TSD', 'full_office_name' => 'Technical Services Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Zurbito Street, Masbate City',]);
        redts_f_offices::create(['id' => 120, 'region_id' => 7, 'slug' => 'R5-PENRO-Masbate-TSD-Conservation', 'office' => 'P.Masbate.CDS', 'full_office_name' => 'Conservation and Development Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Zurbito Street, Masbate City',]);
        redts_f_offices::create(['id' => 121, 'region_id' => 7, 'slug' => 'R5-PENRO-Masbate-TSD-RLPDS', 'office' => 'P.Masbate.RPS', 'full_office_name' => 'PENRO Masbate Regulation and Permitting Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Zurbito Street, Masbate City',]);
        redts_f_offices::create(['id' => 122, 'region_id' => 7, 'slug' => 'R5-PENRO-Masbate-TSD-Enforcement', 'office' => 'P.Masbate.Enforcement', 'full_office_name' => 'Enforcement Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Zurbito Street, Masbate City',]);
        redts_f_offices::create(['id' => 123, 'region_id' => 7, 'slug' => 'R5-PENRO-Sorsogon-MSD', 'office' => 'P.Sor.MSD', 'full_office_name' => 'Management Services Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'B. Road, Sorsogon City, Sorsogon',]);
        redts_f_offices::create(['id' => 124, 'region_id' => 7, 'slug' => 'R5-PENRO-Sorsogon-MSD-Admin', 'office' => 'P.Sor.Admin', 'full_office_name' => 'Administrator Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'B. Road, Sorsogon City, Sorsogon',]);
        redts_f_offices::create(['id' => 125, 'region_id' => 7, 'slug' => 'R5-PENRO-Sorsogon-MSD-Finance', 'office' => 'P.Sor.Finance', 'full_office_name' => 'Finance Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'B. Road, Sorsogon City, Sorsogon',]);
        redts_f_offices::create(['id' => 126, 'region_id' => 7, 'slug' => 'R5-PENRO-Sorsogon-MSD-Planning', 'office' => 'P.Sor.PMS', 'full_office_name' => 'Planning and Management Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'B. Road, Sorsogon City, Sorsogon',]);
        redts_f_offices::create(['id' => 127, 'region_id' => 7, 'slug' => 'R5-PENRO-Sorsogon-MSD-Records', 'office' => 'P.Sor.Records', 'full_office_name' => 'Records Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'B. Road, Sorsogon City, Sorsogon',]);
        redts_f_offices::create(['id' => 128, 'region_id' => 7, 'slug' => 'R5-PENRO-Sorsogon-TSD', 'office' => 'P.Sor.TSD', 'full_office_name' => 'Technical Services Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'B. Road, Sorsogon City, Sorsogon',]);
        redts_f_offices::create(['id' => 129, 'region_id' => 7, 'slug' => 'R5-PENRO-Sorsogon-TSD-Conservation', 'office' => 'P.Sor.CDS', 'full_office_name' => 'Conservation and Development Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'B. Road, Sorsogon City, Sorsogon',]);
        redts_f_offices::create(['id' => 130, 'region_id' => 7, 'slug' => 'R5-PENRO-Sorsogon-TSD-RLPDS', 'office' => 'P.Sor.RPS', 'full_office_name' => 'PENRO Sorsogon Regulation and Permitting Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'B. Road, Sorsogon City, Sorsogon',]);
        redts_f_offices::create(['id' => 131, 'region_id' => 7, 'slug' => 'R5-PENRO-Sorsogon-TSD-Enforcement', 'office' => 'P.Sor.Enforcement', 'full_office_name' => 'Enforcement Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'B. Road, Sorsogon City, Sorsogon',]);
        redts_f_offices::create(['id' => 132, 'region_id' => 7, 'slug' => 'R5-CENRO-Guinobatan-CDS', 'office' => 'C.Gbtn.CDS', 'full_office_name' => 'Conservation and Development Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Morera, Guinobatan, Albay',]);
        redts_f_offices::create(['id' => 133, 'region_id' => 7, 'slug' => 'R5-CENRO-Guinobatan-RLPDS', 'office' => 'C.Gbtn.RPS', 'full_office_name' => 'CENRO Guinobatan Regulation and Permitting Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Morera, Guinobatan, Albay',]);
        redts_f_offices::create(['id' => 134, 'region_id' => 7, 'slug' => 'R5-CENRO-Guinobatan-Enforcement', 'office' => 'C.Gbtn.Enforcement', 'full_office_name' => 'Enforcement Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Morera, Guinobatan, Albay',]);
        redts_f_offices::create(['id' => 135, 'region_id' => 7, 'slug' => 'R5-CENRO-Guinobatan-Records', 'office' => 'C.Gbtn.Records', 'full_office_name' => 'Records Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Morera, Guinobatan, Albay',]);
        redts_f_offices::create(['id' => 136, 'region_id' => 7, 'slug' => 'R5-CENRO-Iriga-CDS', 'office' => 'C.Iriga.CDS', 'full_office_name' => 'Conservation and Development Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Iriga City, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 137, 'region_id' => 7, 'slug' => 'R5-CENRO-Iriga-RLPDS', 'office' => 'C.Iriga.RPS', 'full_office_name' => 'CENRO Iriga Regulation and Permitting Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Iriga City, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 138, 'region_id' => 7, 'slug' => 'R5-CENRO-Iriga-Enforcement', 'office' => 'C.Iriga.Enforcement', 'full_office_name' => 'Enforcement Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Iriga City, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 139, 'region_id' => 7, 'slug' => 'R5-CENRO-Iriga-Records', 'office' => 'C.Iriga.Records', 'full_office_name' => 'Records Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Iriga City, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 140, 'region_id' => 7, 'slug' => 'R5-CENRO-Goa-CDS', 'office' => 'C.Goa.CDS', 'full_office_name' => 'Conservation and Development Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Catagbacan, Goa, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 141, 'region_id' => 7, 'slug' => 'R5-CENRO-Goa-RLPDS', 'office' => 'C.Goa.RPS', 'full_office_name' => 'CENRO Goa Regulation and Permitting Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Catagbacan, Goa, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 142, 'region_id' => 7, 'slug' => 'R5-CENRO-Goa-Enforcement', 'office' => 'C.Goa.Enforcement', 'full_office_name' => 'Enforcement Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Catagbacan, Goa, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 143, 'region_id' => 7, 'slug' => 'R5-CENRO-Goa-Records', 'office' => 'C.Goa.Records', 'full_office_name' => 'Records Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Catagbacan, Goa, Camarines Sur',]);  //updated
        redts_f_offices::create(['id' => 144, 'region_id' => 7, 'slug' => 'R5-CENRO-Sipocot-CDS', 'office' => 'C.Sipocot.CDS', 'full_office_name' => 'Conservation and Development Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Andaya Highway, Sipocot, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 145, 'region_id' => 7, 'slug' => 'R5-CENRO-Sipocot-RLPDS', 'office' => 'C.Sipocot.RPS', 'full_office_name' => 'CENRO Sipocot Regulation and Permitting Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => '',]); //updated
        redts_f_offices::create(['id' => 146, 'region_id' => 7, 'slug' => 'R5-CENRO-Sipocot-Enforcement', 'office' => 'C.Sipocot.Enforcement', 'full_office_name' => 'Enforcement Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Andaya Highway, Sipocot, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 147, 'region_id' => 7, 'slug' => 'R5-CENRO-Sipocot-Records', 'office' => 'C.Sipocot..Records', 'full_office_name' => 'Records Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Andaya Highway, Sipocot, Camarines Sur',]); //updated 
        redts_f_offices::create(['id' => 148, 'region_id' => 7, 'slug' => 'R5-CENRO-Mobo-CDS', 'office' => 'C.Mobo.CDS', 'full_office_name' => 'Conservation and Development Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Medina St, Mobo, Masbate',]);
        redts_f_offices::create(['id' => 149, 'region_id' => 7, 'slug' => 'R5-CENRO-Mobo-RLPDS', 'office' => 'C.Mobo.RPS', 'full_office_name' => 'CENRO Mobo Regulation and Permitting Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Medina St, Mobo, Masbate',]); //updated
        redts_f_offices::create(['id' => 150, 'region_id' => 7, 'slug' => 'R5-CENRO-Mobo-Enforcement', 'office' => 'C.Mobo.Enforcement', 'full_office_name' => 'Enforcement Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Medina St, Mobo, Masbate',]); //updated
        redts_f_offices::create(['id' => 151, 'region_id' => 7, 'slug' => 'R5-CENRO-Mobo-Records', 'office' => 'C.Mobo.Records', 'full_office_name' => 'Records Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Medina St, Mobo, Masbate',]); //updated
        redts_f_offices::create(['id' => 152, 'region_id' => 7, 'slug' => 'R5-CENRO-SanJacinto-CDS', 'office' => 'C.SJ.CDS', 'full_office_name' => 'Conservation and Development Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Burgos, San Jacinto, Masbate',]); //updated
        redts_f_offices::create(['id' => 153, 'region_id' => 7, 'slug' => 'R5-CENRO-SanJacinto-RLPDS', 'office' => 'C.SJ.RPS', 'full_office_name' => 'CENRO San Jacinto Regulation and Permitting Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Burgos, San Jacinto, Masbate',]); //updated
        redts_f_offices::create(['id' => 154, 'region_id' => 7, 'slug' => 'R5-CENRO-SanJacinto-Enforcement', 'office' => 'C.SJ.Enforcement', 'full_office_name' => 'Enforcement Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Burgos, San Jacinto, Masbate',]); //updated
        redts_f_offices::create(['id' => 155, 'region_id' => 7, 'slug' => 'R5-CENRO-SanJacinto-Records', 'office' => 'C.SJ.Records', 'full_office_name' => 'Records Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Burgos, San Jacinto, Masbate',]); //updated
        redts_f_offices::create(['id' => 156, 'region_id' => 7, 'slug' => 'R5-DENREU', 'office' => 'DENREU', 'full_office_name' => 'DENREU', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 157, 'region_id' => 7, 'slug' => 'R5-CANVASSER-ORED', 'office' => 'Canvass.ORED', 'full_office_name' => 'ORED', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 158, 'region_id' => 7, 'slug' => 'R5-CANVASSER-OARDMS', 'office' => 'Canvass.OARDMS', 'full_office_name' => 'OARDMS', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 159, 'region_id' => 7, 'slug' => 'R5-CANVASSER-OARDTS', 'office' => 'Canvass.OARDTS', 'full_office_name' => 'OARDTS', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 160, 'region_id' => 7, 'slug' => 'R5-BACSEC', 'office' => 'BAC', 'full_office_name' => 'Bids and Awards Committee', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 161, 'region_id' => 7, 'slug' => 'R5-RecvCheck', 'office' => 'RV-RS', 'full_office_name' => 'Regional Office V - Records Section', 'office_type' => 'Receiving', 'mother_unit' => 'NULL', 'header_office_title' => 'NULL', 'office_address' => 'Rawis, Legazpi City',]);
        redts_f_offices::create(['id' => 162, 'region_id' => 7, 'slug' => 'PENROa-RecvCheck', 'office' => 'P.Albay-RS', 'full_office_name' => 'PENRO Albay - Records Section', 'office_type' => 'Receiving', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Legazpi Port District, Legazpi City, Albay',]);
        redts_f_offices::create(['id' => 163, 'region_id' => 7, 'slug' => 'PENROcn-RecvCheck', 'office' => 'P.CNorte-RS', 'full_office_name' => 'PENRO Camarines Norte - Records Section', 'office_type' => 'Receiving', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Dagondan, Daet, Camarines Norte',]);
        redts_f_offices::create(['id' => 164, 'region_id' => 7, 'slug' => 'PENROcs-RecvCheck', 'office' => 'P.CSur-RS', 'full_office_name' => 'PENRO Camarines Sur - Records Section', 'office_type' => 'Receiving', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Panganiban Drive, Naga City, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 165, 'region_id' => 7, 'slug' => 'PENROm-RecvCheck', 'office' => 'P.Masbate-RS', 'full_office_name' => 'PENRO Masbate - Records Section', 'office_type' => 'Receiving', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'Zurbito Street, Masbate City',]);
        redts_f_offices::create(['id' => 166, 'region_id' => 7, 'slug' => 'PENROc-ADFS-RecvCheck', 'office' => 'P.Catnes-RS', 'full_office_name' => 'PENRO Catanduanes - Records Section', 'office_type' => 'Receiving', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'San Isidro Village, Virac, Catanduanes',]);
        redts_f_offices::create(['id' => 167, 'region_id' => 7, 'slug' => 'PENROs-RecvCheck', 'office' => 'P.Sor-RS', 'full_office_name' => 'PENRO Sorsogon - Records Section', 'office_type' => 'Receiving', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'B. Road, Sorsogon City, Sorsogon',]);
        redts_f_offices::create(['id' => 168, 'region_id' => 7, 'slug' => 'PENROa-RecvCheck-CENROguinobatan', 'office' => 'C.Gbtn-RS', 'full_office_name' => 'CENRO Guinobatan - Records Section', 'office_type' => 'Receiving', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Morera, Guinobatan, Albay',]);
        redts_f_offices::create(['id' => 169, 'region_id' => 7, 'slug' => 'PENROcs-RecvCheck-CENROiriga', 'office' => 'C.Iriga-RS', 'full_office_name' => 'CENRO Iriga - Records Section', 'office_type' => 'Receiving', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Iriga City, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 170, 'region_id' => 7, 'slug' => 'PENROcs-RecvCheck-CENROsipocot', 'office' => 'C.Sipocot-RS', 'full_office_name' => 'CENRO Sipocot - Records Section', 'office_type' => 'Receiving', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Andaya Highway, Sipocot, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 171, 'region_id' => 7, 'slug' => 'PENROcs-RecvCheck-CENROgoa', 'office' => 'C.Goa-RS', 'full_office_name' => 'CENRO Goa - Records Section', 'office_type' => 'Receiving', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Catagbacan, Goa, Camarines Sur',]); //updated
        redts_f_offices::create(['id' => 172, 'region_id' => 7, 'slug' => 'PENROm-RecvCheck-CENROmb', 'office' => 'C.Mobo-RS', 'full_office_name' => 'CENRO Mobo - Records Section', 'office_type' => 'Receiving', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Medina St, Mobo, Masbate',]); //updated
        redts_f_offices::create(['id' => 173, 'region_id' => 7, 'slug' => 'PENROm-RecvCheck-CENROsanjacinto', 'office' => 'C.SJacinto-RS', 'full_office_name' => 'CENRO San Jacinto - Records Section', 'office_type' => 'Receiving', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Burgos, San Jacinto, Masbate',]); //updated
        redts_f_offices::create(['id' => 176, 'region_id' => 7, 'slug' => 'R5-CENRO-Guinobatan-Cashier', 'office' => 'C.Gbtn.Cashier', 'full_office_name' => 'CENRO Guinobatan Cashier Section', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'COMMUNITY ENVIRONMENT AND NATURAL RESOUCES', 'office_address' => 'Morera, Guinobatan, Albay',]);
        redts_f_offices::create(['id' => 181, 'region_id' => 7, 'slug' => 'R5-PENRO-Catnes-TSD', 'office' => 'P.Catnes.TSD', 'full_office_name' => 'PENRO Catanduanes Technical Service Division', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'San Isidro Village, Virac, Catanduanes',]);
        redts_f_offices::create(['id' => 182, 'region_id' => 7, 'slug' => 'R5-PENRO-Catnes-ADFS-AccU', 'office' => 'P.Catnes.ADFS-AccU', 'full_office_name' => 'PENRO Catanduanes Accounting Office', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'San Isidro Village, Virac, Catanduanes',]);
        redts_f_offices::create(['id' => 183, 'region_id' => 7, 'slug' => 'R5-PENRO-Catnes-ADFS-Cashier', 'office' => 'P.Catnes.ADFS-Cashier', 'full_office_name' => 'PENRO Catanduanes Cashier Office', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'San Isidro Village, Virac, Catanduanes',]);
        redts_f_offices::create(['id' => 184, 'region_id' => 7, 'slug' => 'R5-PENRO-Catnes-FUU', 'office' => 'P.Catnes.FUU', 'full_office_name' => 'PENRO Catanduanes Forest Utilization Unit', 'office_type' => 'Office', 'mother_unit' => 'NULL', 'header_office_title' => 'PROVINCIAL ENVIRONMENT AND NATURAL RESOURCES', 'office_address' => 'San Isidro Village, Virac, Catanduanes',]);
    }
}
